image:
  repository: registry.cn-hangzhou.aliyuncs.com/snailwalker/s3-fuse-flex-volume
  tag: latest
  pullPolicy: Always
flexVolume:
  pluginDir: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/
